### ISSUE TITLE
The request was aborted: Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by THENNARASU** [swhitley/ERPHelper#86]
Installed the ERP Helper plugin in notepad++ version 8.5.6 in windows 10/64 bit.

Try the plugin install through Plugin admins and the manual dll copy on the plugins folder but both came with the same result.

Wondering if this issue is related to an intermediate cert is added to all certs within the organization.

**Comment by THENNARASU** [comment]
Here is the error.

![image](https://github.com/swhitley/ERPHelper/assets/1154546/5129c26d-5662-4d7f-ba75-0e39cc0b17d2)

**Comment by swhitley** [comment]
Hi - Yes, ERP Helper makes a call out to GitHub when it first starts to check for any updates.  I assume the plugin works for you after that initial error.  

I had a similar issue at a previous employer with Workday Studio.  I had to put in a request to IT to whitelist the Workday domains.  In this case, ERP Helper makes calls to GitHub.com, Workday.com, and MyWorkday.com depending on the feature you're using.

**Comment by swhitley** [comment]
Hoping this has been resolved as an internal company-specific issue.
