### ISSUE TITLE
New environments

### ISSUE THREAD

**Issue by THENNARASU** [swhitley/ERPHelper#88]
I was trying to create the connection to our implementation tenant but the wd5-impl doesn't exist on the environment profile to choose from. So i have forked your repo and added this specific US region (wd5) sandbox tenant alone. For this commit i have requested a Pull request to be reviewed by the developers. Currently the workday listed (review the link below) data center doesn't seem to match with what we have on the WDEnvironments profile. I m more than happy to add the missing ones if that will make it consistent. But for now, i have requested a pull request to merge the commit on my fork to the source repo. 

https://community.workday.com/node/29946

**Comment by swhitley** [comment]
Hi - "wd5" is the domain prefix used in Workday's Portland data center.  Look for the "(Portland)" entries in the tenant environment list.  I pulled this list from a resource in Workday Studio, but I can see how it may be difficult to make the connection and will consider how to improve this in the future.

**Comment by THENNARASU** [comment]
Hi - I looked at the list again and here is what I found

Production (Portland) - wd5-e2
Sandbox (Portland) - wd5-impl-e2
Sandbox Preview (Portland) - wd5-impl-e2
Implementation (Portland) - wd5-impl-e2

Where as I m looking to connect to wd5-impl-services1.

**Comment by swhitley** [comment]
Great - The Portland endpoints are correct for WD5.  I checked the latest version of Workday Studio and the descriptions are better, but the endpoint hasn't changed:

```
<env name="Implementation (WD5)" type="impl">
		<e2-endpoint>wd5-impl-e2.workday.com</e2-endpoint>
		<app-endpoint></app-endpoint>
</env>
```

**Comment by swhitley** [comment]
v1.2.0 has the latest tenant list and includes clear labels for WD5.
